language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1.100
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/nanoservice-build.sh
  - ./scripts/nanoservice-test.sh
after_success:
  - ./scripts/nanoservice-dockerize.sh
notifications:
  email:
    on_success: never
    on_failure: always



