apiVersion: apps/v1
kind: Deployment
metadata:
 name: nanoservice-dpl
spec:
 replicas: 3
 selector:
  matchLabels:
    name: nanoservice
 template:
   metadata:
     labels:
       name: nanoservice
   spec:
     containers:
     - name: nano-service
       image: mehdihadeli/nano-service:dev
       ports:
       - containerPort: 5000